name = "flightway"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "COACH_KV"
id = "14129792fcce40dabe02380aff80d055"
preview_id = "5a3893c3048b45e3a2bf6dfdcca92e65"
